create table person
(
    id                  bigint generated by default as identity primary key,
    name                varchar(200) not null,
    email               varchar(100) not null unique,
    age                 int check (age >= 0 and age < 120),
    weight              int check (weight >= 0 and weight <= 400),
    height              int check (height >= 0 and height <= 300),
    goal                varchar(20),
    calorie_norm        int
);

create table dish
(
    id                  bigint generated by default as identity primary key,
    name                varchar(200) not null unique,
    calories            int check (calories >= 0),
    proteins            numeric(5, 2) check (proteins >= 0),
    fats                numeric(5, 2) check (fats >= 0),
    carbohydrates       numeric(5, 2) check (carbohydrates >= 0)
);

create table meal
(
    id                  bigint generated by default as identity primary key,
    person_id           bigint references person (id),
    meal_type           varchar(20),
    create_date         date
);

create table meal_dish
(
    id                  bigint generated by default as identity primary key,
    meal_id             bigint references meal (id) on delete cascade,
    dish_id             bigint references dish (id) on delete cascade,
    count               int check (count > 0)
);